# Generates include/assets/clock_face.c from the historical Opel dial photo.
#
# Source: ..\..\..\uhr_optimiert.png (1254x1254, dial circle inside a dark
# bezel ring). The bezel is cropped away so the dial fills the whole 240x240
# round display. Colors are flattened to two tones (uniform cream, pure black)
# so no photographic gradients remain. Output is LVGL RGB565A8, identical
# layout to the previous asset (240x240, 172800 bytes).
#
# Usage: python assets/clock/generate_clock_face.py [path\to\uhr_optimiert.png]

import sys
import os

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
HEADUNIT = os.path.abspath(os.path.join(HERE, "..", ".."))
DEFAULT_SRC = os.path.abspath(os.path.join(HEADUNIT, "..", "..", "..", "uhr_optimiert.png"))
OUT_C = os.path.join(HEADUNIT, "include", "assets", "clock_face.c")
OUT_PNG = os.path.join(HERE, "uhr_ziffernblatt_240.png")

SIZE = 240
CENTER = (626.7, 599.6)  # dial center in the source photo
DIAL_R = 502.0           # dial radius: cream face incl. printed ticks, no bezel
CREAM = (233, 202, 153)  # measured flat dial color
BLACK_LUM = 95.0         # luminance at/below which markings are pure black
CREAM_LUM = 165.0        # luminance at/above which the dial is pure cream
HUB_R = 40.0             # brass hub kept as photo (hands cover its center)
HUB_BLEND = 52.0         # hub fades into flattened dial between the two radii


def smoothstep(e0, e1, x):
    t = np.clip((x - e0) / (e1 - e0), 0.0, 1.0)
    return t * t * (3.0 - 2.0 * t)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    im = Image.open(src).convert("RGB")
    a = np.asarray(im).astype(np.float32)

    cx, cy = CENTER
    x0 = int(round(cx - DIAL_R))
    y0 = int(round(cy - DIAL_R))
    side = int(round(2 * DIAL_R))
    crop = a[y0 : y0 + side, x0 : x0 + side]

    # Flatten: uniform cream background, markings as pure black with the
    # luminance ramp only shaping the anti-aliased glyph edges.
    lum = 0.299 * crop[..., 0] + 0.587 * crop[..., 1] + 0.114 * crop[..., 2]
    ink = smoothstep(CREAM_LUM, BLACK_LUM, lum)  # 0 = cream, 1 = black
    flat = np.empty_like(crop)
    for c in range(3):
        flat[..., c] = CREAM[c] * (1.0 - ink)

    # Keep the brass hub photo inside r < HUB_R, blend out to HUB_BLEND.
    yy, xx = np.mgrid[0:side, 0:side].astype(np.float32)
    rad = np.sqrt((xx - (cx - x0)) ** 2 + (yy - (cy - y0)) ** 2)
    hub_mix = smoothstep(HUB_R, HUB_BLEND, rad)[..., None]
    flat = crop * (1.0 - hub_mix) + flat * hub_mix

    img = Image.fromarray(np.clip(flat, 0, 255).astype(np.uint8), "RGB").resize(
        (SIZE, SIZE), Image.LANCZOS
    )

    # Circular alpha so the screen background shows in the corners.
    px = np.asarray(img).astype(np.float32)
    yy, xx = np.mgrid[0:SIZE, 0:SIZE].astype(np.float32)
    edge = SIZE / 2.0 - 0.75 - np.sqrt((xx - (SIZE / 2 - 0.5)) ** 2 + (yy - (SIZE / 2 - 0.5)) ** 2)
    alpha = np.clip(edge / 1.5 + 0.5, 0.0, 1.0)
    rgba = np.dstack([px, (alpha * 255.0).astype(np.uint8)]).astype(np.uint8)
    Image.fromarray(rgba, "RGBA").save(OUT_PNG)

    # LVGL 9 RGB565A8: little-endian RGB565 plane, then 8-bit alpha plane.
    r5 = (rgba[..., 0].astype(np.uint32) * 31 + 127) // 255
    g6 = (rgba[..., 1].astype(np.uint32) * 63 + 127) // 255
    b5 = (rgba[..., 2].astype(np.uint32) * 31 + 127) // 255
    rgb565 = (r5 << 11) | (g6 << 5) | b5
    lo = (rgb565 & 0xFF).astype(np.uint8)
    hi = (rgb565 >> 8).astype(np.uint8)
    payload = bytearray()
    for l, h in zip(lo.flat, hi.flat):
        payload.append(l)
        payload.append(h)
    payload.extend(rgba[..., 3].tobytes())

    lines = []
    for i in range(0, len(payload), 16):
        chunk = payload[i : i + 16]
        lines.append("    " + ",".join(f"0x{b:02X}" for b in chunk) + ",")

    with open(OUT_C, "w", newline="\n") as f:
        f.write(
            "// Auto-generated by assets/clock/generate_clock_face.py\n"
            f"// Source: {os.path.basename(src)} (bezel cropped, colors flattened)\n"
            f"// {SIZE}x{SIZE}, color format LV_COLOR_FORMAT_RGB565A8 "
            "(RGB array + A8 alpha array)\n"
            "// Regenerate: python assets/clock/generate_clock_face.py\n"
            '#include "lvgl.h"\n\n'
            f"const uint8_t clock_face_map[{len(payload)}] = {{\n"
        )
        f.write("\n".join(lines))
        f.write(
            "\n};\n\nconst lv_image_dsc_t clock_face = {\n"
            "    .header = {\n"
            "        .magic = LV_IMAGE_HEADER_MAGIC,\n"
            "        .cf = LV_COLOR_FORMAT_RGB565A8,\n"
            f"        .w = {SIZE},\n        .h = {SIZE},\n    }},\n"
            f"    .data_size = {len(payload)},\n"
            "    .data = clock_face_map,\n};\n"
        )
    print(f"wrote {OUT_C} ({len(payload)} bytes) and {OUT_PNG}")


if __name__ == "__main__":
    main()
