# Generates include/assets/needle_clock_hour.c and needle_clock_min.c from the
# Opel instrument sprite sheet.
#
# Source: ..\..\..\instruments_opel_1_2.png (1536x1024 RGBA). The clock hands
# sit in the needle row (bottom): needle_clock_hour is the short hand with the
# large hub, needle_clock_min the long thin hand. Both are cut out, rotated so
# they point to 12 o'clock, scaled to the 240x240 dial, and emitted as LVGL 9
# RGB565A8 images (same layout as clock_face.c).
#
# Usage: python assets/clock/generate_clock_hands.py [path\to\instruments_opel_1_2.png]

import math
import os
import sys

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
HEADUNIT = os.path.abspath(os.path.join(HERE, "..", ".."))
DEFAULT_SRC = os.path.abspath(os.path.join(HEADUNIT, "..", "..", "..", "instruments_opel_1_2.png"))
OUT_DIR_PNG = HERE
OUT_DIR_C = os.path.join(HEADUNIT, "include", "assets")

# Measured in the source sheet (x0, y0, x1, y1) exclusive, hub pivot (x, y)
# absolute, blade angle in degrees clockwise from 12 o'clock.
HANDS = {
    "hour": {
        "box": (1174, 818, 1280, 877),
        "pivot": (1188.1, 861.6),
        "angle": 64.9,
        "length": 100.4,
    },
    "min": {
        "box": (1288, 794, 1406, 874),
        "pivot": (1299.8, 861.2),
        "angle": 58.6,
        "length": 123.3,
    },
}

# Dial is 240x240 with the minute track at r~114. The sheet hands are shot at
# a larger scale than the sheet dials, so scale by target tip radius instead:
# minute tip r~106 (just inside the track), hour keeps the sheet ratio 0.81.
MINUTE_TIP_R = 106.0
MARGIN = 2


def rotate_to_twelve(src_rgba, pivot, angle_deg, scale):
    """Rotate the sprite so the blade points up and scale it around the pivot.

    Returns (rgba, pivot_x, pivot_y) with the pivot at the hub center.
    """
    a = math.radians(angle_deg)
    cos_a, sin_a = math.cos(a), math.sin(a)

    h, w = src_rgba.shape[:2]
    ys, xs = np.where(src_rgba[..., 3] > 8)
    dx = (xs - pivot[0]).astype(np.float32)
    dy = (ys - pivot[1]).astype(np.float32)

    # Output offset = scale * R(-angle) * source offset (y-down coords).
    ox = (dx * cos_a + dy * sin_a) * scale
    oy = (-dx * sin_a + dy * cos_a) * scale
    up = int(math.ceil(-oy.min())) + MARGIN
    down = int(math.ceil(oy.max())) + MARGIN
    side = int(math.ceil(max(np.abs(ox).max(), 1.0))) + MARGIN

    out_w = 2 * side + 1
    out_h = up + down + 1
    px_out, py_out = side, up

    # Inverse map: source offset = R(angle) * output offset / scale.
    yy, xx = np.mgrid[0:out_h, 0:out_w].astype(np.float32)
    sx = ((xx - px_out) * cos_a - (yy - py_out) * sin_a) / scale + pivot[0]
    sy = ((xx - px_out) * sin_a + (yy - py_out) * cos_a) / scale + pivot[1]

    # Bilinear sample with premultiplied alpha (transparent RGB is garbage).
    prem = src_rgba.astype(np.float32)
    prem[..., 0] *= prem[..., 3] / 255.0
    prem[..., 1] *= prem[..., 3] / 255.0
    prem[..., 2] *= prem[..., 3] / 255.0

    x0 = np.clip(np.floor(sx).astype(np.int32), 0, w - 1)
    y0 = np.clip(np.floor(sy).astype(np.int32), 0, h - 1)
    x1 = np.clip(x0 + 1, 0, w - 1)
    y1 = np.clip(y0 + 1, 0, h - 1)
    fx = np.clip(sx - x0, 0.0, 1.0)[..., None]
    fy = np.clip(sy - y0, 0.0, 1.0)[..., None]

    top = prem[y0, x0] * (1.0 - fx) + prem[y0, x1] * fx
    bot = prem[y1, x0] * (1.0 - fx) + prem[y1, x1] * fx
    out = top * (1.0 - fy) + bot * fy

    alpha = out[..., 3:4]
    rgb = np.where(alpha > 0.5, out[..., :3] / np.maximum(alpha / 255.0, 1e-6), 0.0)
    rgba = np.dstack([np.clip(rgb, 0, 255), np.clip(alpha, 0, 255)]).astype(np.uint8)
    return rgba, px_out, py_out


def emit(name, rgba, pivot):
    h, w = rgba.shape[:2]
    r5 = (rgba[..., 0].astype(np.uint32) * 31 + 127) // 255
    g6 = (rgba[..., 1].astype(np.uint32) * 63 + 127) // 255
    b5 = (rgba[..., 2].astype(np.uint32) * 31 + 127) // 255
    rgb565 = (r5 << 11) | (g6 << 5) | b5
    lo = (rgb565 & 0xFF).astype(np.uint8)
    hi = (rgb565 >> 8).astype(np.uint8)
    payload = bytearray()
    for l, hbyte in zip(lo.flat, hi.flat):
        payload.append(l)
        payload.append(hbyte)
    payload.extend(rgba[..., 3].tobytes())

    lines = []
    for i in range(0, len(payload), 16):
        chunk = payload[i : i + 16]
        lines.append("    " + ",".join(f"0x{b:02X}" for b in chunk) + ",")

    out_c = os.path.join(OUT_DIR_C, f"needle_clock_{name}.c")
    with open(out_c, "w", newline="\n") as f:
        f.write(
            f"// Auto-generated by assets/clock/generate_clock_hands.py\n"
            f"// Source: instruments_opel_1_2.png (needle_clock_{name}, rotated to 12 o'clock)\n"
            f"// {w}x{h}, color format LV_COLOR_FORMAT_RGB565A8 "
            "(RGB array + A8 alpha array)\n"
            "// Regenerate: python assets/clock/generate_clock_hands.py\n"
            '#include "lvgl.h"\n\n'
            f"#define NEEDLE_CLOCK_{name.upper()}_PIVOT_X {pivot[0]}\n"
            f"#define NEEDLE_CLOCK_{name.upper()}_PIVOT_Y {pivot[1]}\n\n"
            f"const uint8_t needle_clock_{name}_map[{len(payload)}] = {{\n"
        )
        f.write("\n".join(lines))
        f.write(
            f"\n}};\n\nconst lv_image_dsc_t needle_clock_{name} = {{\n"
            "    .header = {\n"
            "        .magic = LV_IMAGE_HEADER_MAGIC,\n"
            "        .cf = LV_COLOR_FORMAT_RGB565A8,\n"
            f"        .w = {w},\n        .h = {h},\n    }},\n"
            f"    .data_size = {len(payload)},\n"
            f"    .data = needle_clock_{name}_map,\n}};\n"
        )
    print(f"wrote {out_c} ({len(payload)} bytes, {w}x{h}, pivot {pivot})")


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    im = Image.open(src).convert("RGBA")
    sheet = np.asarray(im)

    scale = MINUTE_TIP_R / HANDS["min"]["length"]
    print(f"scale {scale:.4f} (minute tip r {MINUTE_TIP_R}, hour tip r "
          f"{HANDS['hour']['length'] * scale:.1f})")

    for name, spec in HANDS.items():
        x0, y0, x1, y1 = spec["box"]
        crop = sheet[y0:y1, x0:x1]
        pivot = (spec["pivot"][0] - x0, spec["pivot"][1] - y0)
        rgba, px_out, py_out = rotate_to_twelve(crop, pivot, spec["angle"], scale)

        out_png = os.path.join(OUT_DIR_PNG, f"needle_clock_{name}.png")
        Image.fromarray(rgba, "RGBA").save(out_png)
        print(f"wrote {out_png}")
        emit(name, rgba, (px_out, py_out))


if __name__ == "__main__":
    main()
